# 运行阶段
FROM alpine:latest

# 添加标签信息
LABEL maintainer="cursor-api-maintainer" \
      version="1.0" \
      description="Cursor API Service" \
      architecture="x86_64"

# 设置工作目录
WORKDIR /usr/src/app

# 复制二进制文件
COPY ./target/x86_64-unknown-linux-musl/release/cursor-api ./

# 设置环境变量
ENV AUTH_TOKEN=e4de3277818ec8f0e034e2abc1945f09531576851ae0aec789cd512cb49d9eb0
ENV SHARED_TOKEN=e4de3277818ec8f0e034e2abc1945f09531576851ae0aec789cd512cb49d9eb0
ENV PORT=9999

# 设置权限
RUN chmod +x ./cursor-api

# 暴露端口
EXPOSE 9999

# 设置入口点
ENTRYPOINT ["./cursor-api"] 