name: Docker Build

on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: '是否上传构建产物'
        required: true
        type: boolean
        default: true
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Get version from Cargo.toml
        if: github.event_name == 'workflow_dispatch'
        id: cargo_version
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | cut -d '"' -f2)
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: cursor-api:latest
          outputs: type=docker,dest=cursor-api.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4.6.0
        with:
          name: cursor-api-docker-image
          path: cursor-api.tar
          retention-days: 7