name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Docker
      run: |
        docker version
        
    - name: Build image
      run: |
        docker build -t cursor-api:latest .
        
    - name: Save image
      run: |
        mkdir -p artifacts
        docker save cursor-api:latest > artifacts/cursor-api.tar
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: artifacts/cursor-api.tar
        retention-days: 1