name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: disabled
      DOCKER_BUILDKIT: 0
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        DOCKER_BUILDKIT=0 docker build --platform linux/amd64 --no-cache -t cursor-api:latest .
        
    - name: Test image
      run: |
        docker images
        docker inspect cursor-api:latest
        
    - name: Save Docker image
      run: |
        mkdir -p artifacts
        docker save cursor-api:latest > artifacts/cursor-api.tar
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: artifacts/cursor-api.tar
        retention-days: 1